version: '3'

services:
    # PHP Apache server
    web:
        build: ./worker/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - mysql
        volumes:
            - ./worker:/var/www/html

    # MySQL database
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: t_v
            MYSQL_USER: your_user
            MYSQL_PASSWORD: your_password

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8181:80"
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
