version: '3'

services:
    # PHP Apache server
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - mysql
        volumes:
            - ./../../ci-app:/var/www/html

    # MySQL database
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: t_v
            MYSQL_USER: your_user
            MYSQL_PASSWORD: your_password
