apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-app-deploy
  labels:
    name: ci-app-deploy
    app: ci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-app
  template:
    metadata:
      labels:
        app: ci-app
    spec:
      containers:
      - name: ci-app
        image: {{REGISTRY_BASE_PATH}}/ci-app:{{COMMIT}}
        ports:
        - containerPort: 8282
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: ci-app-service
spec:
    selector:
        app: ci-app
    type: NodePort
    ports:
        - protocol: TCP
          port: 8282
          targetPort: 80
