apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deploy
    labels:
        name: mysql-deploy
        app: ci-app
spec:
    replicas: 1
    selector:
        matchLabels:
            name: mysql-pod
            app: ci-app
    template:
        metadata:
            name: mysql-pod
            labels:
                name: mysql-pod
                app: ci-app
        spec:
            containers:
                -   name: mysql
                    image: mysql:latest
                    ports:
                        -   containerPort: 3306
                    env:
                        -   name: MYSQL_ROOT_PASSWORD
                            value: "root"
                        -   name: MYSQL_USER
                            value: "your_user"
                        -   name: MYSQL_DATABASE
                            value: "t_v"
                        -   name: MYSQL_PASSWORD
                            value: "your_password"

---
apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
        name: mysql-service
        app: ci-app
spec:
    type: LoadBalancer
    ports:
        -   port: 3306
            targetPort: 3306
            protocol: TCP
    selector:
        name: mysql-pod
        app: ci-app
