apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    name: phpmyadmin-deploy
    app: ci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-app
  template:
    metadata:
      labels:
        app: ci-app
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
            - name: PMA_HOST
              value: "mysql-service"
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-service
spec:
    selector:
        app: ci-app
    type: NodePort
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 80
