apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: {{REGISTRY_BASE_PATH}}/worker:{{COMMIT}}
        ports:
        - containerPort: 3099
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: worker-service
spec:
    selector:
        app: worker
    type: NodePort
    ports:
        - protocol: TCP
          port: 3001
          targetPort: 80
